### ISSUE TITLE
Unable to tito tag on first release of package if there is a %changelog in spec file

### ISSUE THREAD

**Issue by Ultimation** [rpm-software-management/tito#346]
Removing %changelog let me tag, and then I could re-add the section to tag again, but I could not do my initial tag.

Didn't work with release or version tagger

~~~~ = sensored information


tito tag --debug
Creating output directory: /tmp/tito
Importing tito.tagger.ReleaseTagger
Using tagger class: <class 'tito.tagger.main.ReleaseTagger'>
Looking for .spec in /data/home/~~~~/rpm/~~~~
Using file: ~~~~.spec
Looking for .spec in /data/home/~~~~/rpm/~~~~
Using file: ~~~~.spec
Command: rpm --eval '%scl'
Status code: 0
Command output: %scl

Command: rpm -q --qf '%{name}
'  --eval '%undefine scl' --specfile /data/home/~~~~/rpm/~~~~/~~~~.spec 2> /dev/null | grep -e '^$' -v | head -1
Status code: 0
Command output: ~~~~

Command: git config --get user.name
Status code: 0
Command output: ~~~~

Command: git config --get user.email
Status code: 0
Command output: ~~~~

Getting latest package info from: /data/home/~~~~rpm/~~~~/.tito/packages/~~~~
Command: awk '{ print $1 ; exit }' /data/home/~~~~rpm/~~~~/.tito/packages/~~~~
Status code: 0
Command output: 2.0.1

Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 203, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 671, in main
    return tagger.run(self.options)
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 114, in run
    self._tag_release()
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 656, in _tag_release
    self._make_changelog()
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 260, in _make_changelog
    last_tag = self._get_new_tag(old_version)
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 553, in _get_new_tag
    suffixed_version = self._get_suffixed_version(self._get_version(version_and_release))
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 561, in _get_version
    return version_and_release.split('-')[-2]
IndexError: list index out of range


tito-0.6.11-1.el7.noarch
CentOS Linux release 7.5.1804 (Core)

**Comment by jmrodri** [comment]
@Ultimation what did your `%changelog` look like when this error happened?

**Comment by Ultimation** [comment]
It had just %changelog and a single new line after it. 

Using the tar.gz from here in the same dir, https://github.com/intel/libipt/releases/tag/v2.0.1

```
Name: libipt
Version: 2.0.1
Release: 1%{dist}
Summary: Intel Processor Trace decoder library

License: BSD
URL: https://github.com/intel/libipt
Source0: %{name}-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}
BuildRequires: cmake gcc-c++ pandoc

ExclusiveArch: x86_64

%description
The Intel Processor Trace (Intel PT) Decoder Library is Intel's reference
implementation for decoding Intel PT.  It can be used as a standalone library
or it can be partially or fully integrated into your tool.

%prep
%setup -q -n %{name}-%{version}


%build
%cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
       -DPTUNIT:BOOL=ON \
       -DMAN:BOOL=ON \
       -DDEVBUILD:BOOL=ON \
       .
make VERBOSE=1 %{?_smp_mflags}


%install
make install DESTDIR=%{buildroot}


    
%check
ctest -V %{?_smp_mflags}

%files
%doc README
%license LICENSE
%{_includedir}/intel-pt.h
%{_libdir}/%{name}.so*
%{_mandir}/man3/*



%changelog

```

**Comment by FrostyX** [comment]
I am unable to reproduce the issue now, the changelog is successfully generated for this spec file on `tito tag`. Seems fixed :-)
