### ISSUE TITLE
make prompt less aggressive

### ISSUE THREAD

**Issue by StykMartin** [rpm-software-management/tito#364]
Today I was working on release.
I accidentaly wrote `yy` instead of `y` and whole release was killed.
I guess it would be better to get user a chance to retry? 

```python
Do you wish to proceed with commit? [y/n] yy
Fine, you're on your own!
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tito/cli.py", line 598, in main
    scratch=self.options.scratch)
  File "/usr/lib/python3.7/site-packages/tito/release/distgit.py", line 77, in release
    self._git_release()
  File "/usr/lib/python3.7/site-packages/tito/release/distgit.py", line 101, in _git_release
    self._git_user_confirm_commit(self.package_workdir)
  File "/usr/lib/python3.7/site-packages/tito/release/distgit.py", line 199, in _git_user_confirm_commit
    sys.exit(1)
SystemExit: 1
```

**Comment by FrostyX** [comment]
Hello @StykMartin, thank you for the report.
I've added the issue to the next milestone, so it should get fixed soon.
