### ISSUE TITLE
FetchBuilder broken with no tgz_dir

### ISSUE THREAD

**Issue by ehelms** [rpm-software-management/tito#367]
This breaks the FetchBuilder as it makes the presumption that tgz_dir is defined for all builders inheriting BaseBuilder without defining a sane default:

```
      File "/usr/bin/tito", line 11, in <module>
        load_entry_point('tito==0.6.13', 'console_scripts', 'tito')()
      File "/usr/lib/python3.7/site-packages/tito/cli.py", line 895, in main
        CLI().main(sys.argv[1:])
      File "/usr/lib/python3.7/site-packages/tito/cli.py", line 203, in main
        return module.main(argv)
      File "/usr/lib/python3.7/site-packages/tito/cli.py", line 598, in main
        scratch=self.options.scratch)
      File "/usr/lib/python3.7/site-packages/tito/release/main.py", line 463, in release
        self._koji_release()
      File "/usr/lib/python3.7/site-packages/tito/release/main.py", line 528, in _koji_release
        builder.srpm(dist=disttag)
      File "/usr/lib/python3.7/site-packages/tito/builder/main.py", line 227, in srpm
        self._copy_extra_sources()
      File "/usr/lib/python3.7/site-packages/tito/builder/main.py", line 209, in _copy_extra_sources
        src = os.path.join(self.rpmbuild_sourcedir, self.tgz_dir, source)
    AttributeError: 'FetchBuilder' object has no attribute 'tgz_dir'
```

**Comment by FrostyX** [comment]
Thank you for the report @ehelms,
can you please give me some example of how to reproduce it?

**Comment by ehelms** [comment]
First, here is the command we use:

```
tito release --yes --scratch koji-foreman-jenkins --arg jenkins_job=foreman-develop-source-release --arg jenkins_url=https://ci.theforeman.org
```

If you want to use our packaging, you can clone https://github.com/theforeman/foreman-packaging/tree/rpm/develop and run the command above from `packages/foreman/foreman`

**Comment by ehelms** [comment]
Looks like introduction of copy_extra_sources has caused another breakage as well:

```
  command:
  - tito
  - release
  - --yes
  - koji-katello
  directory: /home/ehelms/workspace/upstream/foreman-packaging/packages/katello//nodejs-react-helmet
  msg: Failed to tito release
  output: |-
    Creating output directory: /tmp/tito
    Will release to the following targets: koji-katello
    Releasing to target: koji-katello
    Working in: /tmp/tito/release-nodejs-react-helmetb57vfwb6
    Building release in Koji...
    Traceback (most recent call last):
      File "/usr/bin/tito", line 11, in <module>
        load_entry_point('tito==0.6.13', 'console_scripts', 'tito')()
      File "/usr/lib/python3.7/site-packages/tito/cli.py", line 895, in main
        CLI().main(sys.argv[1:])
      File "/usr/lib/python3.7/site-packages/tito/cli.py", line 203, in main
        return module.main(argv)
      File "/usr/lib/python3.7/site-packages/tito/cli.py", line 598, in main
        scratch=self.options.scratch)
      File "/usr/lib/python3.7/site-packages/tito/release/main.py", line 463, in release
        self._koji_release()
      File "/usr/lib/python3.7/site-packages/tito/release/main.py", line 528, in _koji_release
        builder.srpm(dist=disttag)
      File "/usr/lib/python3.7/site-packages/tito/builder/main.py", line 227, in srpm
        self._copy_extra_sources()
      File "/usr/lib/python3.7/site-packages/tito/builder/main.py", line 214, in _copy_extra_sources
        shutil.copy(src, self.rpmbuild_sourcedir)
      File "/usr/lib64/python3.7/shutil.py", line 248, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/usr/lib64/python3.7/shutil.py", line 120, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tito/rpmbuild-nodejs-react-helmet240jke8v/SOURCES/nodejs-react-helmet-5.2.0/https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz'
```

The specfile in question -- https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/katello/nodejs-react-helmet/nodejs-react-helmet.spec
