### ISSUE TITLE
Error building RPMs with recent spectool 1.1.0

### ISSUE THREAD

**Issue by vfreex** [rpm-software-management/tito#393]
Got this error when building openshift rpm on Fedora 33 with spectool 1.1.0:

```sh
Cleaning up /tmp/tito/rpmbuild-openshift-clientskh8zq86y
  ; err=Traceback (most recent call last):
  File "/usr/bin/tito", line 33, in <module>
    sys.exit(load_entry_point('tito==0.6.15', 'console_scripts', 'tito')())
  File "/usr/lib/python3.9/site-packages/tito/cli.py", line 902, in main
    CLI().main(sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/tito/cli.py", line 209, in main
    return module.main(argv)
  File "/usr/lib/python3.9/site-packages/tito/cli.py", line 602, in main
    releaser.release(dry_run=self.options.dry_run,
  File "/usr/lib/python3.9/site-packages/tito/release/distgit.py", line 78, in release
    self._git_release()
  File "/usr/lib/python3.9/site-packages/tito/release/distgit.py", line 96, in _git_release
    self.builder.copy_extra_sources()
  File "/usr/lib/python3.9/site-packages/tito/builder/main.py", line 516, in copy_extra_sources
    shutil.copy(src, self.rpmbuild_sourcedir)
  File "/usr/lib64/python3.9/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.9/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: "/tmp/tito/rpmbuild-openshift-clientskh8zq86y/SOURCES/openshift-clients-git-3088.c0a9e25/warning: line 68: It's not recommended to have unversioned Obsoletes: Obsoletes:      atomic-openshift-clients-redistributable"
```

Did some troubleshooting work and found it is because latest version of `spectool` prints warnings about unversioned Obsoletes:

```
$ spectool -S ./oc.spec
warning: line 54: It's not recommended to have unversioned Obsoletes: Obsoletes:      atomic-openshift-clients
warning: line 67: It's not recommended to have unversioned Obsoletes: Obsoletes:      atomic-openshift-clients-redistributable
Source0: https://github.com/openshift/oc/archive/35e8e0cc19a037995231cb71331ba6ac81240ae3/%{name}-0.0.1.tar.gz
```

However `tito` mistakenly parsed the warning message as source file names. See https://github.com/rpm-software-management/tito/blob/998f7fb067aef2e357a175c511b18825faa88892/src/tito/builder/main.py#L504

It seems to me those warning messages are written to stderr, so a simple fix is changing the implementation of running external commands there from `getoutput` call to `subprocess.Popen` to exclude stderr.

**Comment by vfreex** [comment]
Oh, the master has fixed this issue. I am closing this.

**Comment by FrostyX** [comment]
Thank you for testing the `master` branch.
Are you blocked by this issue? Do we need to hurry with a new release, or is it an option for you to use the build from master until then?

**Comment by vfreex** [comment]
@FrostyX No, not in a hurry. it only happens on my dev environment and I am ok with using master branch for now.
