### ISSUE TITLE
Compat for python27 urlrequest is in urllib not urlparse

### ISSUE THREAD

**Issue by mtinberg** [rpm-software-management/tito#424]
https://github.com/rpm-software-management/tito/blob/4c4b1268b3eb1f8cf24074d31ae7690c9643ffbc/src/tito/compat.py#L30

I think a search/replace went awry as `from urlparse import urlretrieve` doesn't work but `from urllib import urlretrieve` does work.  This broken on update for my CentOS7 build host.

**Comment by adwpc** [comment]
same issue:

```
tito
Traceback (most recent call last):
  File "/usr/bin/tito", line 9, in <module>
    load_entry_point('tito==0.6.21', 'console_scripts', 'tito')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 24, in <module>
    from tito.common import find_git_root, error_out, debug, get_class_by_name, \
  File "/usr/lib/python2.7/site-packages/tito/common.py", line 33, in <module>
    from tito.compat import getstatusoutput
  File "/usr/lib/python2.7/site-packages/tito/compat.py", line 30, in <module>
    from urlparse import urlretrieve
ImportError: cannot import name urlretrieve
```

**Comment by FrostyX** [comment]
Thank you for the report,
I am fixing it in PR #426
