### ISSUE TITLE
Allow `tito build --test` to use downloaded source code

### ISSUE THREAD

**Issue by LecrisUT** [rpm-software-management/tito#450]
# Description

Currently `tito build --test` packages the current git repo and substitutes it to the `SOURCE0`. This is helpful for developing and debugging in-source projects where `.spec` file is included with the project. But if the source is external, e.g. a package hosted on `src.fedoraproject.org`, then this approach fails because there is no source code there.

# Proposal

Add a flag or two to determine if `build --test` should treat the `.spec` file as in-source or out-of-source

**Comment by xsuchy** [comment]
Already implemented. See https://github.com/rpm-software-management/tito/blob/master/doc/builders.md#titobuilderfetchbuilder 

Although for dist-git use case is maybe more suitable `pull_from_upstream` of Packit service https://packit.dev/posts/pull-from-upstream/

**Comment by LecrisUT** [comment]
Hmm, how do I link it to the source defined in the `.spec` file?
```
$ tito build --srpm --test
Creating output directory: /tmp/tito
Building package [python-scikit-build-core-]
Fetching sources...
Traceback (most recent call last):
  File "/usr/bin/tito", line 33, in <module>
    sys.exit(load_entry_point('tito==0.6.22', 'console_scripts', 'tito')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tito/cli.py", line 910, in main
    CLI().main(sys.argv[1:])
  File "/usr/lib/python3.11/site-packages/tito/cli.py", line 209, in main
    return module.main(argv)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tito/cli.py", line 392, in main
    return builder.run(self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tito/builder/main.py", line 162, in run
    self.srpm()
  File "/usr/lib/python3.11/site-packages/tito/builder/main.py", line 221, in srpm
    self.tgz()
  File "/usr/lib/python3.11/site-packages/tito/builder/fetch.py", line 67, in tgz
    source_strat.fetch()
  File "/usr/lib/python3.11/site-packages/tito/builder/fetch.py", line 128, in fetch
    manual_sources = [self.builder.args['source'][0]]
                      ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'source'
```
