### ISSUE TITLE
AttributeError: 'rpm.hdr' object has no attribute 'dsOfHeader'

### ISSUE THREAD

**Issue by jflorian** [rpm-software-management/tito#481]
I'm using the YumRepoReleaser via tito-0.6.24-2.fc39.noarch and this is happening:

```
Wrote:
  /tmp/tito/jtbox-0.15-2.git.5.f7041a4.fc39.noarch.rpm
rsync -rlvz /mnt/florian-repos/test/f39/x86_64/ /tmp/tito/yumrepo-svquhs1w
copy: /tmp/tito/jtbox-0.15-2.git.5.f7041a4.fc39.noarch.rpm > /tmp/tito/yumrepo-svquhs1w
Traceback (most recent call last):
  File "/usr/bin/tito", line 33, in <module>
    sys.exit(load_entry_point('tito==0.6.24', 'console_scripts', 'tito')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 910, in main
    CLI().main(sys.argv[1:])
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 209, in main
    return module.main(argv)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 610, in main
    releaser.release(dry_run=self.options.dry_run,
  File "/usr/lib/python3.12/site-packages/tito/release/main.py", line 287, in release
    self.process_packages(temp_dir)
  File "/usr/lib/python3.12/site-packages/tito/release/main.py", line 379, in process_packages
    self.prune_other_versions(temp_dir)
  File "/usr/lib/python3.12/site-packages/tito/release/main.py", line 403, in prune_other_versions
    self.new_rpm_dep_sets[header['name']] = header.dsOfHeader()
                                            ^^^^^^^^^^^^^^^^^
AttributeError: 'rpm.hdr' object has no attribute 'dsOfHeader'
```

As a temporary workaround, I've commented out the call to prune_other_versions and it will complete successfully.  FWIW, things had been working just fine before I upgraded from F38 to F39.

**Comment by FrostyX** [comment]
Hello @jflorian,
thank you for the report.

I remember dealing with a similar issue recently. I'll dig up the patch and try to do the same here.

**Comment by praiskup** [comment]
See also https://github.com/rpm-software-management/mock/issues/1203
