### ISSUE TITLE
fedora-all alias does not work

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/tito#491]
I changed my releasers.conf to 
```
[fedora-git]
releaser = tito.release.FedoraGitReleaser
# from top to down
branches = fedora-all epel-all
```
Previously, I have there branches enumerated. 

But now I got:

```
$ tito release fedora-git
...
Would you like to edit this commit message? [y/n] n
Proceeding with commit.
fedpkg push
Submitting build: fedpkg build --nowait  
Created task: 113477647
Task info: https://koji.fedoraproject.org/koji/taskinfo?taskID=113477647
Merging branch: 'rawhide' -> 'f38'
git push origin f38:f38
Submitting build: fedpkg build --nowait  
Created task: 113477654
Task info: https://koji.fedoraproject.org/koji/taskinfo?taskID=113477654
Merging branch: 'rawhide' -> 'f39'
git push origin f39:f39
Submitting build: fedpkg build --nowait  
Created task: 113477669
Task info: https://koji.fedoraproject.org/koji/taskinfo?taskID=113477669
Merging branch: 'rawhide' -> 'f41'
ERROR: Error running command: fedpkg switch-branch f41

Status code: 1

Command output: Could not execute switch_branch: Unknown remote branch origin/f41

Traceback (most recent call last):
  File "/usr/bin/tito", line 33, in <module>
    sys.exit(load_entry_point('tito==0.6.25', 'console_scripts', 'tito')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 944, in main
    CLI().main(sys.argv[1:])
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 210, in main
    return module.main(argv)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 650, in main
    releaser.release(dry_run=self.options.dry_run,
  File "/usr/lib/python3.12/site-packages/tito/release/distgit.py", line 93, in release
    self._git_release()
  File "/usr/lib/python3.12/site-packages/tito/release/distgit.py", line 152, in _git_release
    self._git_user_confirm_commit(self.package_workdir)
  File "/usr/lib/python3.12/site-packages/tito/release/distgit.py", line 290, in _git_user_confirm_commit
    run_command("%s switch-branch %s" % (self.cli_tool, branch))
  File "/usr/lib/python3.12/site-packages/tito/common.py", line 305, in run_command
    raise RunCommandException(command, status, output)
tito.exception.RunCommandException: Error running command: fedpkg switch-branch f41
```

**Comment by xsuchy** [comment]
Seems it tries to build to 41 instead of 40 which is branched now.

**Comment by FrostyX** [comment]
As expected, the bug is in the fedora-distro-aliases package:

```python
In [1]: from fedora_distro_aliases import get_distro_aliases
In [2]: aliases = get_distro_aliases()

In [3]: [x.namever for x in aliases["fedora-all"]]
Out[3]: ['fedora-38', 'fedora-39', 'fedora-40', 'fedora-rawhide']

In [4]: [x.branch for x in aliases["fedora-all"]]
Out[4]: ['f38', 'f39', 'rawhide', 'f41']
```

See the strange difference between branches and namevers.

**Comment by FrostyX** [comment]
I am going to close the issue now. It is fixed in the fedora-distro-aliases package
https://github.com/rpm-software-management/fedora-distro-aliases/releases/tag/fedora-distro-aliases-1.3-1
We are just waiting till the bodhi updates drop into stable.
