### ISSUE TITLE
Avoid using the `dnf install -C` option?

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/tito#501]
I often face issues like:
```
Error: Some packages have invalid cache, but cannot be downloaded due to "--cacheonly" option


ERROR: Error running command: sudo dnf install -C -y /tmp/tito/noarch/mock-lvm-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm /tmp/tito/noarch/mock-scm-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm /tmp/tito/noarch/mock-filesystem-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm /tmp/tito/noarch/mock-rpmautospec-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm /tmp/tito/noarch/mock-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm

Status code: 1

Command output: ['Updating Subscription Management repositories.', 'Unable to read consumer identity', '', 'This system is not registered with an entitlement server. You can use subscription-manager to register.', '', 'Last metadata expiration check: 0:15:22 ago on Tue Sep  3 11:40:05 2024.', 'Dependencies resolved.', '==========================================================================================', ' Package                     Arch    Version                           Repository     Size', '==========================================================================================', 'Installing:', ' mock-rpmautospec            noarch  5.6.post1-1.git.3775.78a0e11.fc40 @commandline   16 k', ' mock-scm                    noarch  5.6.post1-1.git.3775.78a0e11.fc40 @commandline   20 k', 'Upgrading:', ' mock                        noarch  5.6.post1-1.git.3775.78a0e11.fc40 @commandline  277 k', ' mock-filesystem             noarch  5.6.post1-1.git.3775.78a0e11.fc40 @commandline   19 k', ' mock-lvm                    noarch  5.6.post1-1.git.3775.78a0e11.fc40 @commandline   26 k', 'Installing dependencies:', ' apr                         x86_64  1.7.3-8.fc40                      fedora        128 k', ' apr-util                    x86_64  1.6.3-16.fc40                     fedora         97 k', ' libserf                     x86_64  1.3.10-5.fc40                     fedora         59 k', ' preproc                     noarch  0.5-10.fc40                       fedora         17 k', ' python3-cached_property     noarch  1.5.2-13.fc40                     fedora         20 k', ' rpkg-macros                 noarch  2.0-8.fc40                        fedora         39 k', ' rpm-git-tag-sort            x86_64  1.0.git.5.0b8afd62-4.fc40         fedora         22 k', ' subversion-libs             x86_64  1.14.3-5.fc40                     fedora        1.5 M', ' utf8proc                    x86_64  2.7.0-7.fc40                      fedora         80 k', 'Installing weak dependencies:', ' apr-util-lmdb               x86_64  1.6.3-16.fc40                     fedora         14 k', ' apr-util-openssl            x86_64  1.6.3-16.fc40                     fedora         16 k', ' cvs                         x86_64  1.11.23-70.fc40                   fedora        598 k', ' rpkg                        noarch  3.3-1.fc40                        updates        97 k', ' subversion                  x86_64  1.14.3-5.fc40                     fedora        1.0 M', '', 'Transaction Summary', '==========================================================================================', 'Install  16 Packages', 'Upgrade   3 Packages', '', 'Total size: 4.0 M', 'Total download size: 3.6 M', 'Downloading Packages:', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/apr-1.7.3-8.fc40.x86_64.rpm: No such file or directory', 'Package "apr-1.7.3-8.fc40.x86_64" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/apr-util-1.6.3-16.fc40.x86_64.rpm: No such file or directory', 'Package "apr-util-1.6.3-16.fc40.x86_64" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/apr-util-lmdb-1.6.3-16.fc40.x86_64.rpm: No such file or directory', 'Package "apr-util-lmdb-1.6.3-16.fc40.x86_64" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/apr-util-openssl-1.6.3-16.fc40.x86_64.rpm: No such file or directory', 'Package "apr-util-openssl-1.6.3-16.fc40.x86_64" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/cvs-1.11.23-70.fc40.x86_64.rpm: No such file or directory', 'Package "cvs-1.11.23-70.fc40.x86_64" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/libserf-1.3.10-5.fc40.x86_64.rpm: No such file or directory', 'Package "libserf-1.3.10-5.fc40.x86_64" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/preproc-0.5-10.fc40.noarch.rpm: No such file or directory', 'Package "preproc-0.5-10.fc40.noarch" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/python3-cached_property-1.5.2-13.fc40.noarch.rpm: No such file or directory', 'Package "python3-cached_property-1.5.2-13.fc40.noarch" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/rpkg-macros-2.0-8.fc40.noarch.rpm: No such file or directory', 'Package "rpkg-macros-2.0-8.fc40.noarch" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/rpm-git-tag-sort-1.0.git.5.0b8afd62-4.fc40.x86_64.rpm: No such file or directory', 'Package "rpm-git-tag-sort-1.0.git.5.0b8afd62-4.fc40.x86_64" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/subversion-1.14.3-5.fc40.x86_64.rpm: No such file or directory', 'Package "subversion-1.14.3-5.fc40.x86_64" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/subversion-libs-1.14.3-5.fc40.x86_64.rpm: No such file or directory', 'Package "subversion-libs-1.14.3-5.fc40.x86_64" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/fedora-6c3a9e5977a00788/packages/utf8proc-2.7.0-7.fc40.x86_64.rpm: No such file or directory', 'Package "utf8proc-2.7.0-7.fc40.x86_64" from repository "fedora" has incorrect checksum', 'Error opening /var/cache/dnf/updates-02a32a5ce99e20ab/packages/rpkg-3.3-1.fc40.noarch.rpm: No such file or directory', 'Package "rpkg-3.3-1.fc40.noarch" from repository "updates" has incorrect checksum', 'Error: Some packages have invalid cache, but cannot be downloaded due to "--cacheonly" option']

Traceback (most recent call last):
  File "/usr/bin/tito", line 33, in <module>
    sys.exit(load_entry_point('tito==0.6.26', 'console_scripts', 'tito')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 944, in main
    CLI().main(sys.argv[1:])
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 210, in main
    return module.main(argv)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 432, in main
    return builder.run(self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/builder/main.py", line 169, in run
    self._auto_install()
  File "/usr/lib/python3.12/site-packages/tito/builder/main.py", line 354, in _auto_install
    run_command_print(cmd)
  File "/usr/lib/python3.12/site-packages/tito/common.py", line 353, in run_command_print
    raise RunCommandException(command, status, "\n".join(output))
tito.exception.RunCommandException: Error running command: sudo dnf install -C -y /tmp/tito/noarch/mock-lvm-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm /tmp/tito/noarch/mock-scm-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm /tmp/tito/noarch/mock-filesystem-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm /tmp/tito/noarch/mock-rpmautospec-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm /tmp/tito/noarch/mock-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm
[mockbuild@ip-172-30-2-126 mock]$ sudo dnf install /tmp/tito/noarch/mock-lvm-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm /tmp/tito/noarch/mock-scm-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm /tmp/tito/noarch/mock-filesystem-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm /tmp/tito/noarch/mock-rpmautospec-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm /tmp/tito/noarch/mock-5.6.post1-1.git.3775.78a0e11.fc40.noarch.rpm
Updating Subscription Management repositories.
Unable to read consumer identity

```

But the task that I want to do is just: `dnf install -y <set of rpms>`.

**Comment by praiskup** [comment]
Oh, you linked 501 to 501, which one is the dupe?

**Comment by praiskup** [comment]
#363 -> closing
